Importing NumPy library

In [1]:
import numpy as np

Initialize a list with some values and converting the list into NumPy 1 Dimensional array (Vector)

In [2]:
list1 = [1,2,3,4]
arr = np.array(list1)

Printing the arr and its data type.

In [3]:
arr

array([1, 2, 3, 4])

In [4]:
arr.dtype

dtype('int64')

Accessing elements of the NumPy array is similar to the accessing List element in Python.

In [5]:
arr[2]

3

In [6]:
arr[0:2]

array([1, 2])

In [7]:
arr[1:]

array([2, 3, 4])

Creating a NumPy matrix from the list of list.

In [8]:
mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
arr2D = np.array(mat)
arr2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Accessing elements of the NumPy matrix is easy and can be done as below.
Elements of the matrix can be accessed by passing the positionn of the element in the brackets ([m,n]) where m is row and n is column.

We can fetch multiple elements by using the slicing property.

In [10]:
arr2D[0]

array([1, 2, 3])

In [11]:
arr2D[0,1]

2

In [12]:
arr2D[0:2,0:3]

array([[1, 2, 3],
       [4, 5, 6]])

Some of the important methods supported by NumPy.

arange -> similar to the range in Python.

zeros -> used to create a N Dimensional array of 0s.

ones -> used to create a N Dimensional array of 1s.

reshape -> converts the existing NumPy array into a new array with different dimensions.

max or min -> to find the maximum and minimum in the array.

argmax or argmin -> to find the index of maximum and minimum in the array.

copy -> to create a copy of the existing array.

In [13]:
arr1 = np.arange(9)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
new_arr = arr1.reshape(3,3)
new_arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
mx = arr1.max()
mx

8

In [18]:
index_max = arr1.argmax()
index_max

8

Basic Operations on Numpy arrays.

In [19]:
#Addition
added_arr = arr + arr
added_arr

array([2, 4, 6, 8])

In [20]:
#Subtraction
subtracted_arr = added_arr - 1.5
subtracted_arr

array([0.5, 2.5, 4.5, 6.5])

In [21]:
bool_arr = added_arr > 3
bool_arr

array([False,  True,  True,  True])

In [22]:
added_arr[bool_arr]

array([4, 6, 8])

In [23]:
added_arr[added_arr > 4]

array([6, 8])

Some of the mathematical funtions supported by NumPy.

Complete list can be found at https://docs.scipy.org/doc/numpy/reference/routines.math.html

In [24]:
log_arr = np.log(added_arr)
log_arr

array([0.69314718, 1.38629436, 1.79175947, 2.07944154])

In [25]:
sin_arr = np.sin(added_arr)
sin_arr

array([ 0.90929743, -0.7568025 , -0.2794155 ,  0.98935825])

In [26]:
exp_arr = np.exp(added_arr)
exp_arr

array([   7.3890561 ,   54.59815003,  403.42879349, 2980.95798704])